version: 2
jobs:
  pre-commit:
    working_directory: ~/path-web
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update && sudo apt-get -f install && sudo apt-get install wget
      - run:
          name: Install Node dependencies
          command: |
            npm install
  uat-push:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Heroku Staging Deploy
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_UAT_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  frontend-deploy:
    jobs:
      - pre-commit:
          filters:
            branches:
              only:
                - master
      - uat-push:
          requires:
            - pre-commit